window.KUSHIRO_SPOTS = [
      { name:'釧路駅', en:'KUSHIRO STATION / CENTRAL', lat:42.99072, lng:144.38210, radius:125, subtitle:'北大通へ続く、釧路の玄関口。', story:'旅の始まりは釧路駅。ここからまっすぐ南へ伸びる北大通が、街と港をつないでいます。' },
      { name:'和商市場', en:'WASHO MARKET / CENTRAL', lat:42.99037, lng:144.37855, radius:115, subtitle:'勝手丼で知られる、港町の台所。', story:'新鮮な魚介をご飯に好きなだけのせる「勝手丼」で知られる市場。釧路の海と食卓が、ここで一つにつながります。' },
      { name:'釧路芸術館', en:'KUSHIRO ART MUSEUM / WATERFRONT', lat:42.98436, lng:144.37687, radius:120, subtitle:'港の気配にひらかれたアートの場所。', story:'港を望むウォーターフロントの美術館。倉庫や船の風景の中に、静かな文化の灯りが置かれています。' },
      { name:'MOO', en:'FISHERMAN\'S WHARF MOO / WATERFRONT', lat:42.98191, lng:144.38337, radius:105, subtitle:'釧路川河畔のウォーターフロント。', story:'幣舞橋のたもとに立つ複合施設。夕暮れ、建物の灯りと川面が重なる時間は空から眺めても格別です。' },
      { name:'幣舞橋', en:'NUSAMAI BRIDGE / WATERFRONT', lat:42.98103, lng:144.38556, radius:105, subtitle:'釧路川と夕日の、街の象徴。', story:'釧路川の最下流に架かる街の象徴。四季像、港へ沈む夕日、霧に浮かぶ街路灯が釧路らしい時間を作ります。' },
      { name:'港文館', en:'KOBUNKAN / WATERFRONT', lat:42.98252, lng:144.39054, radius:115, subtitle:'石川啄木と港の記憶を伝える場所。', story:'釧路に滞在した石川啄木と港の歴史を伝える建物。川沿いの静かな時間に出会えます。' },
      { name:'北海道教育大学 釧路校', en:'HUE KUSHIRO / EAST', lat:42.98134, lng:144.39804, radius:145, subtitle:'城山に広がる教育のキャンパス。', story:'学校教育を支える人材が学ぶ北海道教育大学釧路校。釧路川の東側、城山の街並みにキャンパスが広がります。' },
      { name:'釧路市立博物館', en:'KUSHIRO CITY MUSEUM / HARUTORI', lat:42.97421, lng:144.40348, radius:135, subtitle:'タンチョウを思わせる造形の博物館。', story:'釧路の自然・歴史・アイヌ文化を伝える総合博物館。翼を広げたような建物も空からよく分かります。' },
      { name:'春採湖', en:'LAKE HARUTORI / HARUTORI', lat:42.97222, lng:144.40361, radius:260, subtitle:'街のすぐ隣に残る、海跡湖の自然。', story:'市街地に抱かれた海跡湖。ヒブナや多くの野鳥が暮らし、港町のすぐそばに濃い自然が残っています。' },
      { name:'米町公園', en:'YONEMACHI PARK / SOUTH', lat:42.97488, lng:144.37223, radius:145, subtitle:'高台から港を見渡す、古い釧路の丘。', story:'釧路発祥の地とされる米町の高台。港と市街、海へ落ちていく丘の輪郭を一望できます。' },
      { name:'ユタカアイスアリーナ', en:'KUSHIRO ICE ARENA / TOTTORI', lat:43.01333, lng:144.36000, radius:165, subtitle:'氷都くしろを象徴するリンク。', story:'アイスホッケーとスケートの街・釧路を象徴する屋内リンク。鳥取地区の大きなランドマークです。' },
      { name:'釧路公立大学', en:'KUSHIRO PUBLIC UNIVERSITY / ASHINO', lat:43.01832, lng:144.39633, radius:175, subtitle:'芦野に広がる経済学のキャンパス。', story:'ひがし北海道の地域に根ざす釧路公立大学。整った街区の中にキャンパスと緑地が広がります。' },
      { name:'鳥取神社', en:'TOTTORI SHRINE / WEST', lat:43.01405, lng:144.34730, radius:155, subtitle:'鳥取地区の歴史を見守る神社。', story:'釧路の西側、鳥取地区の歩みを見守ってきた神社。周囲の住宅街と境内の緑が鮮やかな対比を作ります。' },
      { name:'釧路大規模運動公園', en:'SPORTS PARK / EAST', lat:43.03280, lng:144.41120, radius:280, subtitle:'競技施設が集まる広大な運動拠点。', story:'陸上競技場や球場などが集まる広大なスポーツエリア。上空からは各施設の形が一目で分かります。' },
      { name:'釧路高専', en:'NIT KUSHIRO COLLEGE / OTANOSHIKENISHI', lat:43.015902, lng:144.261255, radius:190, subtitle:'大楽毛西にある、ものづくりと技術の学び舎。', story:'釧路工業高等専門学校。機械・情報・電気電子・建築など、未来を形にする技術者たちが学ぶキャンパスです。' },
      { name:'大楽毛駅', en:'OTANOSHKE STATION / WEST', lat:43.00940, lng:144.27380, radius:145, subtitle:'海と湿原の間を走る根室本線の駅。', story:'釧路市西部の大楽毛地区にある駅。鉄路が海岸線と市街地を結び、釧路高専への玄関口にもなっています。' },
      { name:'釧路港 西港区', en:'KUSHIRO WEST PORT / COAST', lat:42.99350, lng:144.31850, radius:420, subtitle:'物流を支える巨大な港湾空間。', story:'大型船と広い埠頭が並ぶ西港区。釧路が海と産業によって発展してきたことを、空から実感できます。' },
      { name:'たんちょう釧路空港', en:'KUSHIRO AIRPORT / TSURUOKA', lat:43.04083, lng:144.19278, radius:420, subtitle:'ひがし北海道の空の玄関口。', story:'海岸から内陸へ入った丘陵に伸びる滑走路。釧路と全国を空でつなぐ広域交通の拠点です。' },
      { name:'釧路市丹頂鶴自然公園', en:'TANCHO CRANE PARK / TSURUOKA', lat:43.05624, lng:144.19629, radius:260, subtitle:'一年を通してタンチョウに出会える公園。', story:'自然に近い環境でタンチョウを保護・飼育する公園。世界で初めてタンチョウの人工ふ化に成功した場所です。' },
      { name:'釧路市動物園', en:'KUSHIRO CITY ZOO / AKAN', lat:43.08124, lng:144.23651, radius:380, subtitle:'北海道の動物たちと出会う広大な園。', story:'国内最東端に位置する動物園。北海道らしい動物と自然を、広大な敷地の中で感じられます。' },
      { name:'釧路市湿原展望台', en:'MARSH OBSERVATORY / HOKUTO', lat:43.07397, lng:144.32075, radius:280, subtitle:'釧路湿原を西側から見渡す代表的な拠点。', story:'湿原植物ヤチボウズを思わせる建物と遊歩道。屋上から湿原と阿寒の山々を広く見渡せます。' },
      { name:'細岡展望台', en:'HOSOOKA VIEWPOINT / MARSH EAST', lat:43.10530, lng:144.44840, radius:320, subtitle:'蛇行する釧路川と湿原の大展望。', story:'釧路湿原を東側から望む展望地。蛇行する釧路川と広大な湿原、遠い山並みが一つの景色になります。' },
      { name:'達古武湖', en:'LAKE TAKKOBU / MARSH EAST', lat:43.07080, lng:144.48760, radius:500, subtitle:'湿原東部に水をたたえる静かな湖。', story:'釧路湿原の東側にある湖。森林と湿地、水辺がつながる風景を上空から楽しめます。' },
      { name:'岩保木水門', en:'IWABOKKI WATER GATE / MARSH', lat:43.17050, lng:144.45350, radius:420, subtitle:'湿原の治水史を語る二つの水門。', story:'釧路川の治水の歴史を伝える新旧の水門。湿原の中に人の営みの痕跡が静かに残ります。' },
      { name:'阿寒国際ツルセンター', en:'AKAN CRANE CENTER / AKAN', lat:43.14337, lng:144.14898, radius:300, subtitle:'タンチョウの研究と保護を担う専門施設。', story:'タンチョウの生態研究・保護・情報発信を行う専門施設。冬には多くの野生のタンチョウが集まります。' },
      { name:'阿寒湖温泉', en:'LAKE AKAN ONSEN / AKAN', lat:43.43268, lng:144.09592, radius:420, subtitle:'湖と雄阿寒岳を望む温泉街。', story:'阿寒湖の南岸に広がる温泉街。湖、森、火山と温泉文化が重なる、釧路市最北部の大きな目的地です。' },
      { name:'阿寒湖アイヌコタン', en:'AINU KOTAN / LAKE AKAN', lat:43.43560, lng:144.08670, radius:260, subtitle:'アイヌ文化を伝える湖畔の集落。', story:'木彫や舞踊、暮らしの文化を伝える阿寒湖畔のコタン。森と湖に根ざした文化が息づいています。' },
      { name:'雄阿寒岳', en:'MT. OAKAN / AKAN', lat:43.45360, lng:144.16420, radius:650, subtitle:'阿寒湖の東にそびえる火山。', story:'阿寒湖の東に端正な姿でそびえる雄阿寒岳。広域飛行の北端を示す、圧倒的な自然のランドマークです。' },
      { name:'音別駅', en:'ONBETSU STATION / ONBETSU', lat:42.88902, lng:143.93172, radius:220, subtitle:'釧路市西端・音別地区の鉄道拠点。', story:'現在の釧路市域の西端に近い音別地区。海沿いを走る根室本線と町の暮らしを結ぶ駅です。' }
    ];
